Source/Common/Glasswall.CloudProxy.Common/Web/Abstraction/CloudProxyController.cs, Source/Service/Constants.cs, Source/Service/Controllers/AnalyseController.cs, Source/Service/Controllers/FileTypeDetectionController.cs, Source/Service/Controllers/RebuildController.cs, Source/Service/Startup.cs
Added custom header in response related to [Feature](https://github.com/k8-proxy/cs-k8s-api/issues/9)
=> Api implementation

static/media/api.205bac47.yaml
- Added open-api spec for zipfile endpoint
=> Added open-api spec for zipfile

Source/Service/Constants.cs, Source/Service/Controllers/AnalyseController.cs, Source/Service/Controllers/RebuildController.cs
changes related to [xmlreport endpoint](https://github.com/k8-proxy/cs-k8s-api/issues/37)
=> xmlreport api added

Source/Service/Constants.cs, Source/Service/Controllers/AnalyseController.cs, Source/Service/Glasswall.CloudProxy.Api.csproj, Source/Service/Startup.cs, Source/Service/Utilities/IZipUtility.cs, Source/Service/Utilities/ZipUtility.cs
Changes related to [41](https://github.com/k8-proxy/cs-k8s-api/issues/41)
=> rebuildzip endpoint added

Source/Service/Controllers/HealthController.cs
Added health check endpoint regarding [issue 42](https://github.com/k8-proxy/cs-k8s-api/issues/42)
=> Health endpoint added

Source/Common/Glasswall.CloudProxy.Common/AdaptationService/AdaptationOutcome.cs, Source/Common/Glasswall.CloudProxy.Common/AdaptationService/AdaptationOutcomeProcessor.cs, Source/Common/Glasswall.CloudProxy.Common/AdaptationService/AdaptionCache.cs, Source/Common/Glasswall.CloudProxy.Common/AdaptationService/RabbitMqClient.cs, Source/Common/Glasswall.CloudProxy.Common/ReturnOutcome.cs, Source/Common/Glasswall.CloudProxy.Common/Setup/ServiceCollectionExtensionMethods.cs, Source/Common/Glasswall.CloudProxy.Common/Web/Models/GWallInfo.cs, Source/Service/Controllers/AnalyseController.cs, Source/Service/Controllers/FileTypeDetectionController.cs, Source/Service/Controllers/RebuildController.cs, Source/Service/LocalEntryPoint.cs, Source/Service/Startup.cs, Source/Service/Utilities/FileUtility.cs, Source/Service/Utilities/ZipUtility.cs
Implementation of [30](https://github.com/k8-proxy/cs-k8s-api/issues/30), Added `protectedzipfile `endpoint
=> Support password protected zip

Source/Service/Controllers/RebuildController.cs
=> Add protection in response

Source/Common/Glasswall.CloudProxy.Common/ClientType.cs, Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Common/Glasswall.CloudProxy.Common/EnumExtensions.cs, Source/Common/Glasswall.CloudProxy.Common/Glasswall.CloudProxy.Common.csproj, Source/Common/Glasswall.CloudProxy.Common/Web/Abstraction/CloudProxyController.cs, Source/Common/Glasswall.CloudProxy.Common/Web/Models/UserAgentInfo.cs, Source/Service/Controllers/AnalyseController.cs, Source/Service/Controllers/FileTypeDetectionController.cs, Source/Service/Controllers/HealthController.cs, Source/Service/Controllers/RebuildController.cs, Source/Service/Startup.cs, Source/Test/Glasswall.CloudProxy.IntegrationTest/ControllerTests/AnalyseControllerTests.cs, Source/Test/Glasswall.CloudProxy.IntegrationTest/ControllerTests/FileTypeDetectionControllerTests.cs, Source/Test/Glasswall.CloudProxy.IntegrationTest/ControllerTests/RebuildControllerTests.cs, Source/Test/Glasswall.CloudProxy.IntegrationTest/CustomWebApplicationFactory.cs
Correlated files processed in the Web and Desktop apps with the Elastic Logs [26](https://github.com/k8-proxy/cs-k8s-api/issues/26)
=> correlate files processed in the Web and Desktop apps with the Elastic Logs

Source/Service/Controllers/AnalyseController.cs, Source/Service/Controllers/FileTypeDetectionController.cs, Source/Service/Controllers/RebuildController.cs
=> Header changes

deployment.yaml
updated docker image in deployment file
=> updated docker image in deployment file

Source/Service/Startup.cs
=> Disabled Jaeger

Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Service/Controllers/AnalyseController.cs, Source/Service/Controllers/FileTypeDetectionController.cs, Source/Service/Controllers/RebuildController.cs
Changes related to [75](https://github.com/k8-proxy/cs-k8s-api/issues/75)
=> issue-75 changes

Integration/Filedrop.md
Updated file-drop deployment document
=> Samarthdd readme

Source/Common/Glasswall.CloudProxy.Common/ConfigLoaders/VersionConfigLoader.cs, Source/Common/Glasswall.CloudProxy.Common/Configuration/IVersionConfiguration.cs, Source/Common/Glasswall.CloudProxy.Common/Configuration/VersionConfiguration.cs, Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Common/Glasswall.CloudProxy.Common/Glasswall.CloudProxy.Common.csproj, Source/Common/Glasswall.CloudProxy.Common/Setup/ServiceCollectionExtensionMethods.cs, Source/Common/Glasswall.CloudProxy.Common/Utilities/FileUtility.cs, Source/Common/Glasswall.CloudProxy.Common/Utilities/IFileUtility.cs, Source/Common/Glasswall.CloudProxy.Common/Utilities/IZipUtility.cs, Source/Common/Glasswall.CloudProxy.Common/Utilities/ZipUtility.cs, Source/Service/Controllers/AnalyseController.cs, Source/Service/Controllers/DetailController.cs, Source/Service/Controllers/FileTypeDetectionController.cs, Source/Service/Controllers/RebuildController.cs, Source/Service/Glasswall.CloudProxy.Api.csproj, Source/Service/Startup.cs
Changes regarding [53](https://github.com/k8-proxy/cs-k8s-api/issues/53) and [65](https://github.com/k8-proxy/cs-k8s-api/issues/65)
=> issue 53 and 65 changes

Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Service/Controllers/HealthController.cs
Changes regarding [92](https://github.com/k8-proxy/cs-k8s-api/issues/92)
Updated api version
=> Changes regarding #92

Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Common/Glasswall.CloudProxy.Common/Utilities/EnumExtensions.cs, Source/Common/Glasswall.CloudProxy.Common/Utilities/StringExtensions.cs, Source/Common/Glasswall.CloudProxy.Common/Web/Models/UserAgentInfo.cs, Source/Service/Controllers/AnalyseController.cs
Changes of [104](https://github.com/k8-proxy/cs-k8s-api/issues/104)
=> New apis added #104

Integration/Filedrop_AWS.md
=> Samarthdd patch 1

Integration/Esxi-deployment.md
-Added instruction on how to manually edit  `service-cluster-ip.txt` , `monitoring-password.txt` , `logging-password.txt` , `cluster.txt` 
-Moved "Password extraction" in the beginning of integration instructions so that user will have the passwords ready before needing them.
=> Changes in Esxi-deployment.md

deployment.yaml
Temporary solution for memory leak issue
=> Update deployment.yaml to add readiness and liveness probes

Source/Service/StaticFiles/openapi.json
Addressed language relating to permitted used of product names by removing d-First
=> Farringtonp patch 1

Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Common/Glasswall.CloudProxy.Common/Web/Abstraction/CloudProxyController.cs, Source/Common/Glasswall.CloudProxy.Common/Web/Models/CloudProxyResponseModel.cs, Source/Common/Glasswall.CloudProxy.Common/Web/Models/ICloudProxyResponseModel.cs, Source/Service/Controllers/AnalyseController.cs, Source/Service/Controllers/FileTypeDetectionController.cs, Source/Service/Controllers/RebuildController.cs
https://github.com/k8-proxy/cs-k8s-api/pull/211#issue-660055806
=> [MERGE Develop into main]

Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Common/Glasswall.CloudProxy.Common/FileType.cs, Source/Common/Glasswall.CloudProxy.Common/Utilities/FileUtility.cs, Source/Common/Glasswall.CloudProxy.Common/Utilities/IFileUtility.cs, Source/Common/Glasswall.CloudProxy.Common/Web/Abstraction/CloudProxyController.cs, Source/Common/Glasswall.CloudProxy.Common/Web/Models/FileTypeDetectionResponse.cs, Source/Service/Controllers/RebuildController.cs
Changes for https://github.com/k8-proxy/cs-k8s-api/issues/210
=> Changes for #210

Source/Common/Glasswall.CloudProxy.Common/Glasswall.CloudProxy.Common.csproj, Source/Service/Glasswall.CloudProxy.Api.csproj, Source/Test/Glasswall.CloudProxy.IntegrationTest/Glasswall.CloudProxy.IntegrationTest.csproj
Fixed code vulnerabilities of https://github.com/k8-proxy/cs-k8s-api/issues/320
Remaining the deployment file one and assigned to @gurunathg 
CC: @GINAGC
=> Fixed System.Text.Encodings.Web Synk vulnerability

Source/Common/Glasswall.CloudProxy.Common/ConfigLoaders/CloudSdkConfigLoader.cs, Source/Common/Glasswall.CloudProxy.Common/Configuration/CloudSdkConfiguration.cs, Source/Common/Glasswall.CloudProxy.Common/Configuration/ICloudSdkConfiguration.cs, Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Common/Glasswall.CloudProxy.Common/Setup/ServiceCollectionExtensionMethods.cs, Source/Service/Controllers/RebuildController.cs, Source/Service/Startup.cs
Changes for https://github.com/k8-proxy/cs-k8s-api/issues/304
Changes for https://github.com/k8-proxy/cs-k8s-api/issues/359
=> Changes for #304 and #359

Source/Common/Glasswall.CloudProxy.Common/ConfigLoaders/CloudSdkConfigLoader.cs, Source/Common/Glasswall.CloudProxy.Common/Configuration/CloudSdkConfiguration.cs, Source/Common/Glasswall.CloudProxy.Common/Configuration/ICloudSdkConfiguration.cs, Source/Common/Glasswall.CloudProxy.Common/Constants.cs, Source/Common/Glasswall.CloudProxy.Common/Setup/ServiceCollectionExtensionMethods.cs, Source/Service/Startup.cs
Changes reverted of https://github.com/k8-proxy/cs-k8s-api/issues/304
=> Reverted changes of #304
